OPENAI_API_ENDPOINT = "https://tsi-open-ai.openai.azure.com/"
OPENAI_API_KEY = "ad6b509e5bc2429c9640a54ad0c67edc"
OPENAI_API_VERSION= "2023-08-01-preview"
OPENAI_API_TYPE = "azure"
OPENAI_DEPLOYMENT_NAME = "gpt-4"
OPENAI_MODEL_NAME= "gpt-4"

AZURE_SEARCH_SERVICE = "https://disa-poc-cognitive-search.search.windows.net"
AZURE_SEARCH_INDEX = "azureblob-index-proposals"  
AZURE_SEARCH_API_KEY = "zRZAnmyiqrJj6aviwWxbNiGOCH429zYzyOUGsN5OwyAzSeDJS6C0"

SNOWFLAKE_USER = "CMORGANS"
SNOWFLAKE_PASSWORD = "wph5heq*vey0zfm5MFX"
SNOWFLAKE_ACCOUNT = "dwelhqr-uc83181"
SNOWFLAKE_WAREHOUSE = "PROPOSAL_BOT"
SNOWFLAKE_DATABASE = "PROPOSAL_BOT" 
SNOWFLAKE_SCHEMA = "PUBLIC"

CLIENT_ID = "1c2bae00-61f1-4425-93dc-b9184cafbdfc"
CLIENT_SECRET = "hLW8Q~TOuD_YUoqANuEcv4iTGvKsDZ4_3m64Nb4Z"
TENANT_ID = "c555206a-d80b-4da0-8e10-abdc9b731e4f"